import React from 'react'
import Text from './Text'

const TimeCheck = ({ date, time, data }: any) => {
    return (
        <Text
            text={
                date === 'in 10 days'
                    ? '10 days left'
                    : date === 'in 9 days'
                    ? '9 days left'
                    : date === 'in 8 days'
                    ? '8 days left'
                    : date === 'in 7 days'
                    ? '7 days left'
                    : date === 'in 6 days'
                    ? '6 days left'
                    : date === 'in 5 days'
                    ? '5 days left'
                    : date === 'in 4 days'
                    ? '4 days left'
                    : date === 'in 3 days'
                    ? '3 days left'
                    : date === 'yesterday'
                    ? '2 days left'
                    : time === 'in 24 hours'
                    ? '24 hours left'
                    : time === 'in 23 hours'
                    ? '23 hours left'
                    : time === 'in 22 hours'
                    ? '22 hours left'
                    : time === 'in 21 hours'
                    ? '21 hours left'
                    : time === 'in 20 hours'
                    ? '20 hours left'
                    : time === 'in 19 hours'
                    ? '19 hours left'
                    : time === 'in 18 hours'
                    ? '18 hours left'
                    : time === 'in 17 hours'
                    ? '17 hours left'
                    : time === 'in 16 days'
                    ? '16 days left'
                    : time === 'in 15 days'
                    ? '15 days left'
                    : time === 'in 14 days'
                    ? '14 days left'
                    : time === 'in 13 days'
                    ? '13 days left'
                    : time === 'in 12 days'
                    ? '12 days left'
                    : time === 'in 11 days'
                    ? '11 days left'
                    : time === 'in 10 hours'
                    ? '10 hours left'
                    : time === 'in 9 hours'
                    ? '9 hours left'
                    : time === 'in 8 hours'
                    ? '8 hours left'
                    : time === 'in 7 hours'
                    ? '7 hours left'
                    : time === 'in 6 hours'
                    ? '6 hours left'
                    : time === 'in 5 hours'
                    ? '5 hours left'
                    : time === 'in 4 hours'
                    ? '4 hours left'
                    : time === 'in 3 hours'
                    ? '3 hours left'
                    : time === 'in 2 hours'
                    ? '2 hours left'
                    : time === 'in 1 hours'
                    ? '1 hour left'
                    : data
            }
        />
    )
}

export default TimeCheck
